"""Add permissions

Revision ID: 73393d61a2f9
Revises: 9967ec7d0829
Create Date: 2025-10-05 12:32:57.070095

"""

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from advanced_alchemy.types import (
    GUID,
    ORA_JSONB,
    DateTimeUTC,
    EncryptedString,
    EncryptedText,
    StoredObject,
)
from alembic import op
from sqlalchemy import Text  # noqa: F401

if TYPE_CHECKING:
    pass

__all__ = ["downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades"]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText
sa.StoredObject = StoredObject

# revision identifiers, used by Alembic.
revision = "73393d61a2f9"
down_revision = "9967ec7d0829"
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()


def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()


def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts_permissions",
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("resource", sa.String(length=64), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="1", nullable=False),
        sa.Column("id", sa.GUID(length=16), nullable=False),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_accounts_permissions")),
    )
    with op.batch_alter_table("accounts_permissions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_accounts_permissions_action"), ["action"], unique=False)
        batch_op.create_index(batch_op.f("ix_accounts_permissions_name"), ["name"], unique=True)
        batch_op.create_index(batch_op.f("ix_accounts_permissions_resource"), ["resource"], unique=False)

    op.create_table(
        "accounts_roles_permissions",
        sa.Column("role_id", sa.GUID(length=16), nullable=False),
        sa.Column("permission_id", sa.GUID(length=16), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["accounts_permissions.id"],
            name=op.f("fk_accounts_roles_permissions_permission_id_accounts_permissions"),
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["accounts_roles.id"],
            name=op.f("fk_accounts_roles_permissions_role_id_accounts_roles"),
        ),
        sa.PrimaryKeyConstraint("role_id", "permission_id", name=op.f("pk_accounts_roles_permissions")),
    )
    # ### end Alembic commands ###


def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("accounts_roles_permissions")
    with op.batch_alter_table("accounts_permissions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_accounts_permissions_resource"))
        batch_op.drop_index(batch_op.f("ix_accounts_permissions_name"))
        batch_op.drop_index(batch_op.f("ix_accounts_permissions_action"))

    op.drop_table("accounts_permissions")
    # ### end Alembic commands ###


def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""


def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
