"""Init

Revision ID: 9967ec7d0829
Revises:
Create Date: 2025-08-10 13:45:24.569205

"""

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from advanced_alchemy.types import (
    GUID,
    ORA_JSONB,
    DateTimeUTC,
    EncryptedString,
    EncryptedText,
    StoredObject,
)
from alembic import op
from sqlalchemy import Text  # noqa: F401

if TYPE_CHECKING:
    pass

__all__ = ["downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades"]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText
sa.StoredObject = StoredObject

# revision identifiers, used by Alembic.
revision = "9967ec7d0829"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()


def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()


def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts_roles",
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="1", nullable=False),
        sa.Column("id", sa.GUID(length=16), nullable=False),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_accounts_roles")),
    )
    with op.batch_alter_table("accounts_roles", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_accounts_roles_name"), ["name"], unique=True)

    op.create_table(
        "accounts_users",
        sa.Column("username", sa.String(length=32), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("fullname", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="1", nullable=False),
        sa.Column("last_login", sa.DateTimeUTC(timezone=True), nullable=True),
        sa.Column("id", sa.GUID(length=16), nullable=False),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_accounts_users")),
    )
    with op.batch_alter_table("accounts_users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_accounts_users_email"), ["email"], unique=True)
        batch_op.create_index(batch_op.f("ix_accounts_users_username"), ["username"], unique=True)

    op.create_table(
        "accounts_users_roles",
        sa.Column("user_id", sa.GUID(length=16), nullable=False),
        sa.Column("role_id", sa.GUID(length=16), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"], ["accounts_roles.id"], name=op.f("fk_accounts_users_roles_role_id_accounts_roles")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["accounts_users.id"], name=op.f("fk_accounts_users_roles_user_id_accounts_users")
        ),
        sa.PrimaryKeyConstraint("user_id", "role_id", name=op.f("pk_accounts_users_roles")),
    )
    # ### end Alembic commands ###


def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("accounts_users_roles")
    with op.batch_alter_table("accounts_users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_accounts_users_username"))
        batch_op.drop_index(batch_op.f("ix_accounts_users_email"))

    op.drop_table("accounts_users")
    with op.batch_alter_table("accounts_roles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_accounts_roles_name"))

    op.drop_table("accounts_roles")
    # ### end Alembic commands ###


def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""


def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
