FROM node:lts-slim AS build

RUN corepack enable

WORKDIR /app
COPY ./ .
RUN pnpm install --frozen-lockfile
RUN pnpm run build


FROM node:lts-slim AS runtime

WORKDIR /app

COPY --from=build /app/.output /app/.output

RUN adduser --uid 922 --system --no-create-home app

EXPOSE 3000

ENV HOST=0.0.0.0
ENV PORT=3000
ENV NODE_ENV=production

USER app

CMD ["node", ".output/server/index.mjs"]
